name: Android NDK Build

on:
  push:
    branches: [ main ]   # 推送到 main 自动构建
  workflow_dispatch:     # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 缓存 NDK r27d
      - name: Restore Android NDK cache
        id: restore-ndk 
        uses: actions/cache/restore@v4  
        with:
          path: $HOME/android-ndk-r27d
          key: ndk-r27d-linux   # NDK 缓存 Key

      # 3️⃣ 仅当未命中缓存时下载并解压 NDK
      - name: Download Android NDK r27d
        if: steps.restore-ndk.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip -q android-ndk-r27d-linux.zip -d $HOME

      # 4️⃣ 将 NDK 添加到 PATH
      - name: Add NDK to PATH
        run: echo "$HOME/android-ndk-r27d" >> $GITHUB_PATH

      # 5️⃣ 编译
      - name: Build with ndk-build
        run: |
          $HOME/android-ndk-r27d/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=Android.mk \
            NDK_APPLICATION_MK=Application.mk \
            -j$(nproc)

      # 6️⃣ 保存缓存
      - name: Save Android NDK cache
        if: steps.restore-ndk.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: $HOME/android-ndk-r27d
          key: ndk-r27d-linux

      # 6️⃣ 上传构建产物
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndk-output
          path: |
            libs/**
            obj/**
