name: Android NDK Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 恢复缓存
      - name: Restore Android NDK cache
        id: restore-ndk
        uses: actions/cache/restore@v4
        with:
          path: $HOME/android-ndk-r27d
          key: ndk-r27d-linux

      # 3️⃣ 未命中缓存时下载并解压
      - name: Download Android NDK r27d
        if: steps.restore-ndk.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip -q android-ndk-r27d-linux.zip -d $HOME

      # 4️⃣ 调试：列出 NDK 解压目录 ← 新增
      - name: Debug NDK path
        run: |
          echo "HOME is: $HOME"
          echo "--- List HOME ---"
          ls -la $HOME
          echo "--- List NDK dir ---"
          ls -la $HOME/android-ndk-r27d || echo "NDK dir missing!"

      # 5️⃣ 将 NDK 添加到 PATH
      - name: Add NDK to PATH
        run: echo "$HOME/android-ndk-r27d" >> $GITHUB_PATH

      # 6️⃣ 编译
      - name: Build with ndk-build
        run: |
          $HOME/android-ndk-r27d/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=Android.mk \
            NDK_APPLICATION_MK=Application.mk \
            -j$(nproc)

      # 7️⃣ 保存缓存（目录存在且非空时） ← 修改
      - name: Save Android NDK cache
        if: steps.restore-ndk.outputs.cache-hit != 'true' && hashFiles('${{ env.HOME }}/android-ndk-r27d/**') != ''
        uses: actions/cache/save@v4
        with:
          path: $HOME/android-ndk-r27d
          key: ndk-r27d-linux

      # 8️⃣ 上传构建产物
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndk-output
          path: |
            libs/**
            obj/**